### PR TITLE
[NLU-1734] "6:45 this evening" is not always detected as "18:45"

### PR DESCRIPTION
**Pull request by ushmau5**

### CODE REVIEW

**Comment by ushmau5** [comment]
`     Running `/Users/omcnally/rustling-ontology-genesys/target/debug/rustling-cli --lang en parse '6:45 this evening' -k Time`
+----+-------------+------------+-------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| ix | log(p)      | p          | text              | Output(OutputValue)                                                                                                                 |
+====+=============+============+===================+=====================================================================================================================================+
| 0  | -0.19688015 | 0.82128906 | 6:45 this evening | Datetime(DatetimeOutput { moment: 2021-02-16T18:45:00+00:00, grain: Minute, precision: Exact, latent: false, datetime_kind: Time }) |
+----+-------------+------------+-------------------+-------------------------------------------------------------------------------------------------------------------------------------+
(base) ip-192-168-0-101:cli omcnally$ `

**Comment by ushmau5** [comment]
` 
+----+-------------+------------+-------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| ix | log(p)      | p          | text              | Output(OutputValue)                                                                                                                 |
+====+=============+============+===================+=====================================================================================================================================+
| 0  | -0.19688015 | 0.82128906 | 6:45 this evening | Datetime(DatetimeOutput { moment: 2021-02-16T18:45:00+00:00, grain: Minute, precision: Exact, latent: false, datetime_kind: Time }) |
+----+-------------+------------+-------------------+-------------------------------------------------------------------------------------------------------------------------------------+
 `

**Comment by ushmau5** [comment]
Before fix

`/Users/omcnally/rustling-ontology-genesys/target/debug/rustling-cli --lang en parse '6:45 this evening' -k Time`

`
6:45_____________ | Datetime(DatetimeOutput { moment: 2021-02-16T18:45:00+00:00, grain: Minute, precision: Exact, latent: false, datetime_kind: Time })
`

.
.

`/Users/omcnally/rustling-ontology-genesys/target/debug/rustling-cli --lang en parse '6:45 this morning' -k Time`

`
6:45_____________ | Datetime(DatetimeOutput { moment: 2021-02-16T18:45:00+00:00, grain: Minute, precision: Exact, latent: false, datetime_kind: Time })
`

**Comment by ushmau5** [comment]
After fix

`/Users/omcnally/rustling-ontology-genesys/target/debug/rustling-cli --lang en parse '6:45 this evening' -k Time`

`
6:45 this evening | Datetime(DatetimeOutput { moment: 2021-02-16T18:45:00+00:00, grain: Minute, precision: Exact, latent: false, datetime_kind: Time })
`

.
.

`/Users/omcnally/rustling-ontology-genesys/target/debug/rustling-cli --lang en parse '6:45 this morning' -k Time`

`
6:45 this morning | Datetime(DatetimeOutput { moment: 2021-02-17T06:45:00+00:00, grain: Minute, precision: Exact, latent: false, datetime_kind: Time })
`

**Comment by colm-dillon** [comment]
Let's get it into an alpha build and see how it goes?

**Comment by schutza** [comment]
Burn the boats and switch to LUIS?

**Comment by sanhal** [comment]
that is next in pipeline. @schutza

**Comment by sanhal** [comment]
LGTM

**Review by sanhal — APPROVED** [review]

**Review by colm-dillon — APPROVED** [review]

**Pull request merged**
